name: Build for Easpberry Pi

on:
  # Triggers the workflow, remove the triggers you don't like/want
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: # This one is if you want to manually trigger in the Actions tab, useful to see if it works as intended

jobs:
  buildandpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master' # branch, I think you can remove it
      # https://github.com/docker/setup-qemu-action#usage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      #- name: Available platforms
      #  run: echo ${{ steps.buildx.outputs.platforms }}
      # https://github.com/docker/login-action#docker-hub
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # https://github.com/docker/build-push-action#multi-platform-image
      - name: Build and push TGTG
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          #platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          platforms: linux/arm/v7,linux/arm64 # you can write just "all" if you prefer
          pull: true
          push: true
          tags: |
            marklagendijk/toogoodtogo-watcher:tag_name_that_what_you_want
